import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/Header/Header'
import Footer from './components/Footer/Footer'
import CardProvider from './components/context/CardContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>]
        <CardProvider>
        <Header/>
        {children}
        <div className='fixed bottom-0 w-full'>
          <Footer/>
        </div>
        </CardProvider>
        </body>
    </html>
  )
}
